### ISSUE TITLE
Logo designer

### ISSUE THREAD

**Issue by Bmbailey** [Bmbailey/Baseball#7]
Discuss possible designer options with @nickcannariato and JC.

Friends, acquaintances, anyone who we like that'll hook us up on a great logo for cheap. This is a really important part of our marketing and we need it to look great as well as be a proper representation of the project.

@bmbailey Suggests [Tyler](http://tflem.com) or [Paige](http://paigemillerdesign.com)

**Comment by Bmbailey** [comment]
I mean... We could consider using this [guy](http://imgur.com/a/hWqiC)

His MSPaint skills are pretty legit...

**Comment by birdcar** [comment]
Is it wrong that I'm actually kind of into that idea?

![Why not?](https://media.giphy.com/media/LcOkHfrMAoMDe/giphy.gif)

**Comment by Bmbailey** [comment]
Issue discussion moved to Slack
